---
title: "Frequently Asked Questions"
editor: visual
---

**Who can / should take this course?**

This is a fast-paced and demanding course designed to prepare PhD students for research careers in statistics. Undergraduates and PhD students in other fields are very welcome to take the class, and many have succeeded in the past. But you should be prepared to work hard.

**Can I take this course if I have a conflict with the lecture time?**

Attendance is not taken at lectures but attending is an important part of taking the course. If you want to take another course at the same time, you can do it as long as the other professor is OK with your not attending their lectures.

**How can I prepare for the course?**

The course prerequisites are undergraduate-level linear algebra, real analysis, and a year of upper-division probability and statistics. If you are unsure of your background in one or more of these, the texts below can be useful review materials. All books linked below, except Gelman & Hill, should be available for free with a Berkeley library subscription. Email me if you have trouble accessing them.

-   **Linear algebra:** Fluency with undergrad-level abstract linear algebra is essential to understanding the course content (numerical tools like LU or Cholesky decompositions are not essential). Chapters 1-3 and 5-6 of [Linear Algebra Done Right (Axler)](https://link.springer.com/book/10.1007/978-3-319-11080-6) are good review materials.

-   **Real analysis:** Familiarity with and intuition for ideas of infinite sequences, convergence, Taylor approximations, etc. should be enough. Chapters 1-3 of [Understanding Analysis (Abbott)](https://link.springer.com/book/10.1007/978-1-4939-2712-8) are good review materials.

-   **Probability:** The whole course involves probability. If Chapters 1-6, 8-9, 13-17, and 23 of [Probability for Data Science (Adhikari and Pitman)](http://prob140.org/textbook/) aren't mostly review for you, I strongly recommend studying them before the course begins.

-   **Statistics:** We will derive all statistical results from first principles, but at a fairly technical level. If you have never seen them in an applied context, Chapters 1-6 of *Data Analysis Using Regression and Multilevel/Hierarchical Models* (Gelman & Hill) should give you some frame of reference.
